"""minimum stock

Revision ID: bfd1a5479d8e
Revises: d14d0f5d9216
Create Date: 2026-06-12 17:33:57.865689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd1a5479d8e'
down_revision = 'd14d0f5d9216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_stock', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('minimum_stock')

    # ### end Alembic commands ###
